//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyEmail { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string CompanyMobile { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public bool IsApproved { get; set; }
        public string Password { get; set; }
    }
}
