//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public long MsgID { get; set; }
        public long FromUserID { get; set; }
        public long ToUserID { get; set; }
        public string Msg1 { get; set; }
        public string FilePath { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public bool IsSeen { get; set; }
        public bool IsDeleted { get; set; }
    }
}
