//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public long PojectID { get; set; }
        public string ProjectName { get; set; }
        public string Details { get; set; }
        public string RepoURL { get; set; }
        public long LeaderID { get; set; }
        public System.DateTime DueDT { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public long CreatedByUserID { get; set; }
    }
}
