//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskNote
    {
        public long NoteID { get; set; }
        public long TaskID { get; set; }
        public long CreatedUserID { get; set; }
        public string Note { get; set; }
        public string FilePath { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDT { get; set; }
    }
}
