//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserID { get; set; }
        public long CompanyID { get; set; }
        public string UserName { get; set; }
        public string Designation { get; set; }
        public string UserEmail { get; set; }
        public string Password { get; set; }
        public string UserPhone { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public string About { get; set; }
    }
}
